server: 0.0.0.0:52039
name: mixi server

# User generated password requires uuid,
# so please never change uuid unless you want to lose all users.
uuid: 

database: ./database.db

roomsnames:
  - gobang room 1
  - gobang room 2

